version: '3.8'

services:
#  db:
#    container_name: swimming_gym_db
#    hostname: swimming_gym_db
#    image: postgres:15
#    volumes:
#      - postgres_data:/var/lib/postgresql/data/
#    ports:
#      - "5432:5432"
#    environment:
#      - "POSTGRES_DB=${SQL_DATABASE}"
#      - "POSTGRES_USER=${SQL_USER}"
#      - "POSTGRES_PASSWORD=${SQL_PASSWORD}"
#      - "PGDATA=/var/lib/postgresql/data/pgdata"

  backend:
    build:
      context: .
      dockerfile: swimming_gym/Dockerfile
    container_name: swimming_gym-backend
    command: /start-django
    volumes:
        - ./swimming_gym:/code
    ports:
      - "8000:8000"
    env_file:
      - .env
#    depends_on:
#      - db
    restart: always


#  app_web:
#    container_name: loan-web
#    build:
#      context: .
#      dockerfile: app/Dockerfile
#    image: app_web
#    ports:
#      - 8080:80
#    volumes:
#      - ./app/form/:/usr/local/apache2/htdocs/

volumes:
  postgres_data:
